### PR TITLE
added extra support for data that is outside of the standard property…

### PR DESCRIPTION
**Pull request by RJN368**
… structure, in particular deal associations.

I would like to rewrite the serialization so that it uses the visitor pattern, but for now I have added the opposite to what was added before so you can view the associations.

### CODE REVIEW

**Comment by nover** [comment]
@RJN368 Thanks for the PR.

I think that all the `ToHubSpotDataEntity` / `FromHubSpotDataEntity` should be made virtual in the implementors to allow overrriding them if consumers decide to override the entities that are provided in the library?

**Comment by nover** [comment]
Released as `v0.8.0`

**Comment by RJN368** [comment]
Thanks, I will come back and make some more changes once this project is out the way

**Comment by nover** [comment]
@RJN368 Great, thanks for the contributions so far. If you have bigger changes in mind, perhaps you could contact me via email so we can discuss it (you can find it on my profile) ?

**Comment by nover** [comment]
@RJN368 even better, create an issue with the idea you have and we can have a discussion about it "in the open" :)

**Pull request merged**
