### PR TITLE
Deal Support

### PR DESCRIPTION
**Pull request by RJN368**
This fixes issues with creating deals.  
The first problem was that the API call uses the v2 version rather than the v1 but the request url contains v1, so I introduced a new property.
The second problem was with the amount field which needed to be an int, but the response could not be handled

### CODE REVIEW

**Comment by nover** [comment]
Hi @RJN368 - thanks for the PR, it's really appreciated :)

A few minor things:

1. I'm not particularly fond of the `Merge pull request #1 from skarpdev/master` commit, it would be awesome if you can please rebase your branch with master instead and remove that merge commit (it makes the history much cleaner).
2. The functional test-suite is currently failing so the Pull Request is automatically blocked.

**Comment by RJN368** [comment]
understood thanks, will make the required changes and fix tests

**Comment by nover** [comment]
@RJN368 Cool and again thanks for contributing

**Comment by RJN368** [comment]
OK I'm such a Muppet when it comes to GitHub, I now have 3 sets of changes but I have no idea how to remove the merge from the history.   The first change set contains the changes to support deal creation, the second change adds support for associated ids (don't like this much, I think the Visitor pattern should be used to convert the data structure) and the final commit contains the test fixes.  Sorry to be a pain!

**Comment by nover** [comment]
@RJN368 Okay, no problem - push the changes here and let's have a look :) That initial merge should not stop us from getting the bugs fixed. 

Getting rid of the merge commit would require a bit of rebasing but it can severely destroy your local branch if you are not familiar with it, so let's skip it.
I'm reopening this Pull Request so basically just push your changes.

**Comment by nover** [comment]
@RJN368 Published as version 0.5. Give nuget 10 to 15 minutes to perform their indexing.

**Pull request merged**
